#define S2_ATA_PORT_DATA
#define S2_ATA_PORT_ERROR
#define S2_ATA_PORT_SECNUM

// LBA
#define S2_ATA_PORT_LBALO
#define S2_ATA_PORT_LBAMD
#define S2_ATA_PORT_LBAHI

#define S2_ATA_PORT_DEVICE
#define S2_ATA_PORT_COMMAND
#define S2_ATA_PORT_CONTROL
